name: Deploy to EC2

on: # on defines what triggers the workflow. Here, it's any push to the main branch
  push:
    branches: [ main ]

# GitHub Actions runners are upgrading their underlying system to run on Node.js 24,
# and they are warning developers that older actions (like actions/checkout@v4) are still built using Node.js 20.
# Adding the below to make this future-proof.
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'


# jobs is where you define the work to be done. Each job has a name
# (build-and-deploy, in this case) and runs on a fresh virtual machine
# here, the latest version of Ubuntu
# environment tells the workflow which GitHub environment to use, giving it access to the secrets you configured
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

# steps are the individual tasks that run in sequence.
# Each step either runs a shell command directly using run,
# or pulls in a pre-built action from the GitHub Actions marketplace using uses.
# In this workflow, appleboy/scp-action handles copying files over SSH,
# and appleboy/ssh-action handles running commands on your EC2 instance
# saving you from having to write that plumbing yourself.
# Secrets are referenced with ${{ secrets.YOUR_SECRET_NAME }} and are never exposed in the logs.

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./Dockerfile, ./*.py, ./requirements.txt, ./seeds, ./templates, ./static"
          target: ~/book_store

      - name: Ensure Docker network exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! "$(docker network ls -q -f name=book_store_network)" ]; then
              docker network create book_store_network
            fi

      - name: Ensure database is running
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! "$(docker ps -aq -f name=book_store_db)" ]; then
              docker run \
                --name book_store_db \
                --network book_store_network \
                -e POSTGRES_USER='${{ secrets.POSTGRES_USER }}' \
                -e POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
                -e POSTGRES_DB='book_store' \
                -d postgres:17
              docker exec -i book_store_db psql -U postgres -d book_store < ~/book_store/seeds/books.sql
            fi

      - name: Build Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker build --pull -t book_store:latest ~/book_store

      - name: Deploy new container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "$(docker ps -aq -f name=^book_store$)" ]; then
              docker stop $(docker ps -q -f name=^book_store$) || true
            fi
            docker rm book_store || true
            docker image prune -f || true
            docker run -d \
              --name book_store \
              --network book_store_network \
              --restart unless-stopped \
              -p 5001:5001 \
              book_store:latest
